### ISSUE TITLE
triggerTaskOnSave.tasks Configuration Unclear

### ISSUE THREAD

**Issue by ghost** [Gruntfuggly/triggertaskonsave#11]
The current explanation of the "triggerTaskOnSave.tasks" is unclear. Had to go through the code to understand how it works.

Here's a proposition of explanation.

_Tasks are associated to the files that will trigger the save event, as globs._

eg. 
`"triggerTaskOnSave.tasks": {
        "[Task Name]": [ "[File Path]", "[Other File Path]" ]
    }`

**Comment by nalply** [comment]
Especially the array is important!

**Comment by Gruntfuggly** [comment]
I've updated the README.me to try and clarify the configuration.
