### ISSUE TITLE
Add the ability for exclusion pattern

### ISSUE THREAD

**Issue by i07** [Gruntfuggly/triggertaskonsave#13]
Would be great if we could have the ability to exclude certain folders for the trigger.

**Comment by Gruntfuggly** [comment]
Just uploaded a version which supports exclude globs. Make sure you put them before the other globs in the array as the glob list will stop being processed when it finds a match.

**Comment by i07** [comment]
Awesome, using 0.2.11 confirmed that this is working

```"triggerTaskOnSave.on": true,
"triggerTaskOnSave.restart": true,
"triggerTaskOnSave.selectedTask": "Build and run",
"triggerTaskOnSave.showBusyIndicator": false,
"triggerTaskOnSave.tasks": {
	"build": [
		"!vendor/**",
		"**/*.go",
	]
}
```
thank you for the quick fix. Much appreciated!
