### ISSUE TITLE
If multiple tasks are run on a save, some of their Problem Matchers's are lost to vscode

### ISSUE THREAD

**Issue by desmond-dsouza** [Gruntfuggly/triggertaskonsave#15]
My tasks run Makefile targets and use problem-matchers so VSCode registers task error messages. 

If a save runs multiple tasks (due to overlapping globs) then some tasks' problem-matches are lost to VSCode. If instead I use a single task which does the same thing as the multiple tasks (e.g. by adding a Makefile target that invokes multiple other targets) then all problem-matches are registered correctly with VSCode.

Any ideas?

**Comment by Gruntfuggly** [comment]
It sounds like a vscode issue - I don't know how it decides to clear errors when running a task. Even modifying the extension to run multiple tasks in a sequence would probably have the same effect.

The only thing I can think might be useful would be to sequence the tasks but only proceed to the next task if there were no problems detected in the previous one.

It sounds like using a single task is the only work around at the moment - is there a reason you prefer not to do so?

**Comment by desmond-dsouza** [comment]
A single combined task will work fine. I was just trying to avoid duplication as I still need the separate tasks for manual execution. Thanks!
