### ISSUE TITLE
Tasks not triggered when connecting remotely over SSH

### ISSUE THREAD

**Issue by bbceg** [Gruntfuggly/triggertaskonsave#16]
Hello. Thanks for the plugin.

Anything I could try to ensure tasks are triggered when saving files remotely?

**Comment by bbceg** [comment]
Worked out I was using a user-specific settings.json on the remote. Adding the necessary settings to my local machine's settings.json fixed it. No doubt adding a workspace-specific settings.json would also have done the trick.

**Comment by justinlulejian** [comment]
Hate to resurrect a really old issue but I'm also having this issue. I configured "triggerTaskOnSave.tasks" in my remote's .vscode/settings.json. I have my task in my remote's .vscode/task.json. I can run the task from my local window manually via "Tasks: Run Tasks" but saving a file won't trigger it.

My trigger is for any .h or .cc files:

```
"triggerTaskOnSave.tasks": {
    "my_task": [
        "**/*.h",
        "**/*.cpp",
    ],
}
```

I do have a local settings.json at /Users/<username>/Library/Application Support/Code/User/settings.json. I added "triggerTaskOnSave.tasks" with no change. 

On the extension page it says "Extension is enabled on 'SSH: <my_host>' so it should be running on my remote?

**Comment by bbceg** [comment]
Nothing wrong with reviving an old issue, except the risk of it not being relevant and having to rely on my memory!

I gave up connecting remotely to WSL via VS Code for one reason or another (regular hangs I think did it for me in the end) but, having fired it back up it looks like I had a local settings file on both machines.

So in c:\Users\...\AppData\Roaming\Code\User\settings.json I had:

"triggerTaskOnSave.tasks": {
        "build": [
            "*.scss"
        ],
    },
"triggerTaskOnSave.selectedTask": "Sass Compile",

Hope that helps.
