### ISSUE TITLE
Global tasks are not triggered

### ISSUE THREAD

**Issue by citosid** [Gruntfuggly/triggertaskonsave#17]
According to the documentation, VSCode now supports [global tasks][1]. However, these are not automatically run by the plugin.

I can confirm I can run them manually but not via the plugin.

**Steps to reproduce**

Create a task in 

~/Library/Application Support/Code/User/tasks.json

And configure the plugin to run them automatically.

[1]: https://code.visualstudio.com/updates/v1_42#_user-level-tasks

**Comment by citosid** [comment]
Hello @Gruntfuggly thanks for your work in this awesome tool. Is there any way I could help with this? Maybe give more information or something

**Comment by Gruntfuggly** [comment]
Hi - sorry it's taken a while, but I'm going to get a chance to look at this now.

**Comment by Gruntfuggly** [comment]
I've added a fix. It looks like there is a bug in the global task implementation as the scope seems to come back as "workspace" still, but the fix should be OK.

Let me know how you get on.

**Comment by citosid** [comment]
Thank you so much! It seems that sometimes is working and sometimes it is not, but I'll keep debugging and add more info if needed.

thanks for your hard work!

**Comment by Gruntfuggly** [comment]
Previously it was matching the workspace name against the task, so the fix was to ignore that test if the task scope did not have a name. 
Not sure if that will help understand the problem though... 😕

**Comment by Gruntfuggly** [comment]
Hi any updates on this, or can I close the issue?

**Comment by citosid** [comment]
Hello @Gruntfuggly ! I think you can close it now. It seems to be working ok now.

Thank you for your hard work man!

**Comment by Gruntfuggly** [comment]
Glad you find it useful!
