### ISSUE TITLE
license unclear

### ISSUE THREAD

**Issue by GitMensch** [Gruntfuggly/triggertaskonsave#19]
Please add the license to package.json as documented in https://docs.npmjs.com/files/package.json#license.

Please add the License to the repo as documented in https://help.github.com/articles/adding-a-license-to-a-repository. This is kind of "GitHub standard" and includes the license in this repo's metadata, too.

**Comment by Gruntfuggly** [comment]
Added to latest version.

**Comment by GitMensch** [comment]
Thanks. Now the license is clear. You may consider to redo the steps @ GitHub according to [their documentation](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) which comes down to do the following via Browser in GitHub

* delete License.txt
* click on "add new file"
* naming it LICENSE
* choose the MIT
* add your name and Copyright year
* review and submit

This will mostly make your license-statement "more standard" and both external tools and the GitHub API have it easier to tell what your license actually is.

If you don't want to do this feel free to just close the issue instead.

**Comment by Gruntfuggly** [comment]
Oh cool - I wasn't aware that you could do it via the website. Thanks - will update later.
