### ISSUE TITLE
Add command to allow toggling and/or setting of triggerTaskOnSave.on

### ISSUE THREAD

**Issue by BillDenton** [Gruntfuggly/triggertaskonsave#2]
Rather than going to File, Preferences, Settings and searching for  "triggerTaskOnSave.on" and changing, could you add a command that can be accessed through the command palette. This would allow quick changing of this setting and could be bound to a key.

**Comment by Gruntfuggly** [comment]
Seems sensible - I'll add it in for the next release.

**Comment by Gruntfuggly** [comment]
Added to 0.1.2

**Comment by BillDenton** [comment]
Just confirmed that it works.
