### ISSUE TITLE
Triggers task even without save

### ISSUE THREAD

**Issue by shaunc** [Gruntfuggly/triggertaskonsave#20]
When I have trigger on save enabled, it triggers even when I'm typing before save. This is quite annoying as it sometimes takes away focus from editor window. [Focus may be a problem with the task itself -- so not reporting that as a bug. Also triggering on type might be nice sometimes. However, should be configurable.]

Version 0.2.14, vscode Version: 1.45.0 macos

I have the following configuration:
```json
		"triggerTaskOnSave.tasks": {
			"Behave": [
				"**/*.py",
				"**/*.feature"
			]
		},
		"triggerTaskOnSave.restart": true,
		"triggerTaskOnSave.delay": 500,
		"triggerTaskOnSave.showStatusBarToggle": true
```

**Comment by shaunc** [comment]
Oops -- silly me: I have auto save on! Didn't notice :/

**Comment by Gruntfuggly** [comment]
Glad you got to the bottom of it!
