### ISSUE TITLE
Add configuration to allow automatic closing of terminal after task has run

### ISSUE THREAD

**Issue by U-4-E-A** [Gruntfuggly/triggertaskonsave#21]
Rather than displaying "Terminal will be reused by tasks, press any key to close it.", it would be great if we could configure to auto-close and go back to the command line in the terminal. Thanks.

**Comment by Gruntfuggly** [comment]
That message is generated by VSCode, not the extension. The extension doesn't actually open the terminal window - that's controlled by your task definition.

See https://code.visualstudio.com/Docs/editor/tasks#_output-behavior
