### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by jemand771** [Gruntfuggly/triggertaskonsave#26]
Please consider publishing the extension to the [OpenVSX registry](https://open-vsx.org/)
This allows for using the extension in non-microsoft software such as [VSCodium](https://vscodium.com/) or [GitPod](https://gitpod.io/)

I'm not sure if there are any implications or negative consequences of doing so; you should probably look through the [OpenVSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/) first (I don't fully understand all of it since I don't develop extensions myself)

There's a very detailed guide for publishing extensions available at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension.

**Comment by Gruntfuggly** [comment]
Just published the latest version. 🙂
