### ISSUE TITLE
Does nothing for me -- but why?

### ISSUE THREAD

**Issue by nandoflorestan** [Gruntfuggly/triggertaskonsave#27]
It does not run my build task.  I don't know why.  I can run the build task from the command pallette. Further, this plugin logs this when I change a .ts file:

```
5:55:24 PM Document /home/nando/py/jobs/fairsplit/fair/fair/ui/.vscode/tasks.json saved in workspace ui
5:55:24 PM {}
```

I think part of the problem is I cannot find a complete example of a tasks.json file with this.  The documentation is too terse!

Here's my current file:

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"type": "npm",
			"script": "build",
			"group": "build",
			"problemMatcher": [
				"$eslint-stylish"
			]
		}
	],
	"triggerTaskOnSave.tasks": {
		"build": [
			"src/*",
		],
	},
	"triggerTaskOnSave.showNotifications": true,
	"triggerTaskOnSave.on": true,
}
```

**Comment by Gruntfuggly** [comment]
The "triggerTaskOnSave" settings are extension settings, so should be in your `settings.json`. They won't do anything in the `tasks.json`.

**Comment by nandoflorestan** [comment]
Suggestion: Add that piece of information to the README.

Would you like a pull request?

**Comment by nandoflorestan** [comment]
By the way, I must thank you profusely for your speedy reply.  That was awesome!

**Comment by Gruntfuggly** [comment]
A pull request would be great - I don't have much time at the moment to work on my extensions (and I stupidly published too many of them!).

**Comment by nandoflorestan** [comment]
Done.  Thank you for the code and the support!
