### ISSUE TITLE
Either `No task is currently running.` or `The task 'build' is already active. To terminate it use `Terminate Task...` from the Tasks menu.`

### ISSUE THREAD

**Issue by Southclaws** [Gruntfuggly/triggertaskonsave#5]
Loving this plugin, I'm using it to run a Pawn compiler but I'm hitting some really annoying messages that pop up and I don't really know how to make them hidden.

If I set `triggerTaskOnSave.restart` to `true` then I get:
```
No task is currently running.
```
cover all my tabs at the top of the view when I hit CTRL+S
But if I set that to `false` I get:
```
The task 'build' is already active. To terminate it use `Terminate Task...` from the Tasks menu.
```
whenever I hit CTRL+S during a compilation.

I've also tried all the different `panel` fields in the `task.json` file (new, dedicated and shared) none of them seem to remove these messages.

Hopefully it's a quick fix, I'd prefer to use the `true` option for `triggerTaskOnSave.restart` because these compilations can take up to 2 minutes and if I realise I've made a typo I want to quickly and easily kill the compiler and restart it with my changes.

Thanks for a great plugin!

**Comment by clintmod** [comment]
Ya this doesn't really work right… I would set `triggerTaskOnSave.restart` to `false` and because you can pass multiple tasks to the this plugin as an array you could call a kill task first that kills the compiler if it's running and if it's not running it does nothing. Or you could create a shell script that tries to kill the process by name first and then runs the compiler.

**Comment by Gruntfuggly** [comment]
Yes, unfortunately the available task actions don't quite provide the fine control needed to do this.  With restart set to true, vscode displays the message, and with it set to false, you get the already running message. 

I don't think there is an easy way to find out if a task is currently running.

It would be nice if the terminate just quietly ignored the fact that no tasks are running.

**Comment by Gruntfuggly** [comment]
https://github.com/Microsoft/vscode/issues/45980

Looks like fairly soon we'll have much better control over the tasks, so I'll update the extension when the API is confirmed.

**Comment by Gruntfuggly** [comment]
Sorry it's taken so long, but I've finally updated the extension to work with the new API. It's sill not perfect due to https://github.com/Microsoft/vscode/issues/53331, but that should hopefully be sorted out soon.
