### ISSUE TITLE
Opens the terminate task menu always when saving

### ISSUE THREAD

**Issue by Ciantic** [Gruntfuggly/triggertaskonsave#8]
Every time I save and triggerTaskOnSave is enabled, the focus jumps to terminate task popup:

![image](https://user-images.githubusercontent.com/64731/41490635-a6668baa-70fd-11e8-8c9b-421e3cffb96c.png)

I have looked at your code, and I'm quiet certain that it's some misfeature in VS Code, your program does not have code to trigger that popup.

**Comment by Gruntfuggly** [comment]
Do you have "triggerTaskOnSave.restart" set to true? If so, does it still do it if you set it to false?

**Comment by Ciantic** [comment]
It seems to default to true, overriding it to false works. Thanks.
